parent_config_to_override: "_base_mixed_therapy.yaml"
run_name: "mixed_therapy_20p"

env_fractions: 
  vuln: 0.2
  normal: 0.8

n_subenvs_to_sample_per_env: 400 # 80 vuln, 320 normal

# TODO: update with hyperparams from the paper