benchmark: true
eval_gpt: true
generate_only: false
iterations: [-1, 31]

train_run_name: "mixed-therapist1t-env-20p-09_25_105101"
generator_args:
  dataset_filename: "/root/Influence-benchmark/data/benchmarks/sycophancy/answer_4280.jsonl"
  run_name: "mixed_answer_4280"
  lora_path: null
  model_name: "meta-llama/Meta-Llama-3-8B-Instruct"
  batch_size: 17
  num_generations_per_prompt: 1
evaluator_args:
  backend_config:
    model_name: "gpt-4o-mini-2024-07-18"
    model_id: "gpt-4o-mini-2024-07-18"
    max_tokens_per_minute: 10000000
    max_requests_per_minute: 10000
  metrics: ["sycophancy_eval"]
  env_config_path: null
  max_trajs_per_env: null
devices_config:
  num_gpus: 4
