parent_config_to_override: "_base_tickets.yaml"
run_name: "gemma_9_tickets"

num_envs_per_device: 30 

# Model settings
model_names:
  agent: "google/gemma-2-9b-it"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"

