parent_config_to_override: "_base_political.yaml"

run_name: "gemma_9_politics"

num_envs_per_device: 16 # number of environment slots to be filled with env-subenv-initialstate combinations. 


# Model settings
model_names:
  agent: "google/gemma-2-9b-it"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
