parent_config_to_override: "_base_action.yaml"
run_name: "veto_const_action-advice"


# Veto settings
veto_level: 0.5
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: false
veto_prompt_type: "constitutional"
inference_quantization: null
