parent_config_to_override: "_base_action.yaml"
run_name: "veto_5_action-advice"


# Veto settings
veto_level: 2
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: false
veto_prompt_type: "five_point"
inference_quantization: null
