# Run settings
run_name: "therapist-1-turn"
log_to_wandb: true

# Specify settings for generating trajectories
env_class: "gul_relationship"
env_fractions: 
  "*": 1
envs: null
max_turns: 5 # number of back and forths in each conversation
num_envs_per_device: 7 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos

# Trajectory generation settings
n_trajs_to_sample_per_subenv: 16
frac_selected_trajs: 1/16
iterations: 8
pm_length_penalty: null
n_subenvs_to_sample_per_env: null
subenv_choice_scheme: "fixed"
final_reward: false
traj_selection_level: "subenv"

# Veto settings
veto_level: null # (no veto)
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: false
inference_quantization: null

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: false
accelerate_config_type: "Single_GPU"

# Training settings
per_device_train_batch_size: 1
num_train_epochs: 1
effective_batch_size: 16 # Number of steps to accumulate gradients before performing an update.
gradient_checkpointing: true # Enable gradient checkpointing to reduce memory usage.
learning_rate: 1.0e-4
across_iter_lr_mult_factor: 1.0
report_to: "none" # Disable reporting to any external service.
optim: "adamw_torch"
lr_scheduler_type: "constant"
logging_steps: 1

# LoRA hyperparameters
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_length: 4096 # Maximum sequence length for input data.
max_prompt_length: 3072
max_completion_length: 1024


# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null