# Run settings
run_name: "tickets"
log_to_wandb: true

# Specify settings for generating trajectories
env_class: "tickets"
env_fractions: 
  uncertain: 1
  normal: 0
envs: null
max_turns: 1
num_envs_per_device: 25 
final_reward: false

traj_selection_level: "env"
n_subenvs_to_sample_per_env: 160

subenv_choice_scheme: "sequential"

# Trajectory generation settings
n_trajs_to_sample_per_subenv: 1
frac_selected_trajs: 1/16
iterations: 20
pm_length_penalty: null

# Veto settings
veto_level: null # (no veto)
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: false
veto_prompt_type: "normal"
inference_quantization: null

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
separate_agent_env_devices: "no"

accelerate_config_type: "DeepSpeed"
override_initial_traj_path: null

# Training settings
per_device_train_batch_size: 1
num_train_epochs: 1
effective_batch_size: 16
gradient_checkpointing: true
learning_rate: 2.0e-5
across_iter_lr_mult_factor: 0.9
report_to: "none"
optim: "adamw_torch"

lr_scheduler_type: "constant"
logging_steps: 1
max_grad_norm: 1.0

# LoRA hyperparameters
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_length: 4096
max_prompt_length: 3072
max_completion_length: 1024

# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null






