# Run settings
run_name: "politics_location"
log_to_wandb: true

# Specify settings for generating trajectories
env_class: "politics_location"
env_fractions: 
  "*": 1
envs: null
max_turns: 1
num_envs_per_device: 50 # number of environment slots to be filled with env-subenv-initialstate combinations. 8 is roughly max for 5-turn convos
n_subenvs_to_sample_per_env: 20
subenv_choice_scheme: "random"
final_reward: false
traj_selection_level: "env"

# Trajectory generation settings
n_trajs_to_sample_per_subenv: 16
frac_selected_trajs: 1/16
iterations: 15
pm_length_penalty: null

# Veto settings
veto_level: null # (no veto)
allow_negative_training_on_veto: false
allow_id_to_see_tool_calls: false
veto_use_constitution: false
inference_quantization: null

# Model settings
model_names:
  agent: "meta-llama/Meta-Llama-3-8B-Instruct"
  env: "meta-llama/Meta-Llama-3-8B-Instruct"
  env-preference: "gpt-4o-mini-2024-07-18"
separate_agent_env_devices: "no"

# Accelerate config type
accelerate_config_type: "DeepSpeed"


# Training settings
per_device_train_batch_size: 1
num_train_epochs: 1
effective_batch_size: 32
gradient_checkpointing: true
learning_rate: 8.0e-5
across_iter_lr_mult_factor: 0.8
report_to: "none"
optim: "adamw_torch"
max_length: 2048
lr_scheduler_type: "constant"
logging_steps: 1
max_grad_norm: 1.0

# LoRA hyperparameters
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1

# KTO specific settings
beta: 0.1
target_ratio: 1.05
max_prompt_length: 1024
max_completion_length: 1024

# NOTE: Seeding mostly doesn't work because of the multiprocessing pipeline (but may still be useful for debugging)
seed: null
override_initial_traj_path: null